# Generated by Django 3.0.5 on 2021-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveredAt',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paidAt',
            new_name='paid_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='placedAt',
            new_name='placed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingCost',
            new_name='shipping_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingType',
            new_name='shipping_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
    ]
