# Generated by Django 3.0.5 on 2021-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210607_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'Shipped'), ('3', 'Delivered'), ('4', 'Cancelled')], default='1', max_length=9),
        ),
    ]
